1. Configuration du projet
2. Chargement des données
3. Exploration du corpus
4. Nettoyage
5. Chunking
6. Golden set
7. BM25
8. Dense retrieval
9. Recherche hybride
10. Reranking
11. RAG
12. Outils HLM
13. Agent
14. Évaluation
15. Analyse des erreurs

In [1]:
from google.colab import drive

drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import os

PROJECT_PATH = "/content/drive/MyDrive/Assistant_HLM_RAG"

os.makedirs(PROJECT_PATH, exist_ok=True)

print(PROJECT_PATH)

/content/drive/MyDrive/Assistant_HLM_RAG

In [3]:
import os

folders = [
    "data",
    "data/raw",
    "data/raw/service_public",
    "data/raw/legi",
    "data/raw/rpls",
    "data/raw/dvf",
    "data/raw/plafonds",
    "data/processed",
    "data/indexes",
    "eval",
    "results"
]

for folder in folders:
    path = os.path.join(PROJECT_PATH, folder)
    os.makedirs(path, exist_ok=True)

print("Arborescence créée.")

Arborescence créée.

In [4]:
!pip install -q pandas numpy matplotlib tqdm

In [5]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from pathlib import Path
from tqdm.auto import tqdm

# Assistant HLM — RAG et agent sur données ouvertes

## Objectif

Construire un assistant permettant à un particulier :

1. de comprendre ses droits et démarches concernant le logement social ;
2. de vérifier son éligibilité à un logement social ;
3. de consulter des statistiques sur le parc social d'une commune ;
4. de consulter des informations sur les prix immobiliers d'une commune.

## Architecture envisagée

- RAG documentaire :
  - Service-Public Particuliers
  - Code de la construction et de l'habitation (LEGI)

- Outils structurés :
  - RPLS
  - DVF
  - plafonds PLAI / PLUS / PLS

- Retrieval :
  - BM25
  - Dense retrieval
  - Hybrid retrieval
  - Reranking

- Génération :
  - modèle local

- Évaluation :
  - golden set d'environ 40 questions

In [6]:
sources = pd.DataFrame([
    {
        "source": "Service-Public",
        "type": "Texte",
        "role": "RAG",
        "usage": "Démarches, demande HLM, DALO, APL, SLS, bail"
    },
    {
        "source": "LEGI - Code construction et habitation",
        "type": "Texte juridique",
        "role": "RAG",
        "usage": "Articles relatifs au logement social et à son attribution"
    },
    {
        "source": "RPLS",
        "type": "Données tabulaires",
        "role": "Outil",
        "usage": "Nombre de logements sociaux, vacance, occupation, DPE"
    },
    {
        "source": "DVF",
        "type": "Données tabulaires",
        "role": "Outil",
        "usage": "Prix de vente immobiliers par commune"
    },
    {
        "source": "Plafonds HLM",
        "type": "Barème",
        "role": "Outil",
        "usage": "Calcul d'éligibilité PLAI / PLUS / PLS"
    }
])

sources

,source,type,role,usage
0,Service-Public,Texte,RAG,"Démarches, demande HLM, DALO, APL, SLS, bail"
1,LEGI - Code construction et habitation,Texte juridique,RAG,Articles relatifs au logement social et à son ...
2,RPLS,Données tabulaires,Outil,"Nombre de logements sociaux, vacance, occupati..."
3,DVF,Données tabulaires,Outil,Prix de vente immobiliers par commune
4,Plafonds HLM,Barème,Outil,Calcul d'éligibilité PLAI / PLUS / PLS

Données
   ↓
Nettoyage
   ↓
Chunks
   ↓
Moteur de recherche
   ↓
Évaluation du moteur
   ↓
LLM
   ↓
Agent

In [7]:
golden_questions = pd.DataFrame([
    {
        "id": "q001",
        "type": "rag",
        "question": "Comment déposer une demande de logement social ?",
        "answer": "",
        "gold_docs": []
    },
    {
        "id": "q002",
        "type": "rag",
        "question": "Qu'est-ce que le droit au logement opposable (DALO) ?",
        "answer": "",
        "gold_docs": []
    },
    {
        "id": "q003",
        "type": "eligibility",
        "question": "Avec 28 000 euros de revenus pour un couple avec un enfant à Lyon, suis-je éligible à un logement social ?",
        "answer": "",
        "gold_docs": []
    },
    {
        "id": "q004",
        "type": "rpls",
        "question": "Combien de logements sociaux vacants y a-t-il à Créteil ?",
        "answer": "",
        "gold_docs": []
    },
    {
        "id": "q005",
        "type": "out_of_scope",
        "question": "Quels logements sociaux sont disponibles aujourd'hui à Créteil ?",
        "answer": "Le système ne dispose pas de données en temps réel sur les logements disponibles.",
        "gold_docs": []
    }
])

golden_questions

,id,type,question,answer,gold_docs
0,q001,rag,Comment déposer une demande de logement social ?,,[]
1,q002,rag,Qu'est-ce que le droit au logement opposable (...,,[]
2,q003,eligibility,Avec 28 000 euros de revenus pour un couple av...,,[]
3,q004,rpls,Combien de logements sociaux vacants y a-t-il ...,,[]
4,q005,out_of_scope,Quels logements sociaux sont disponibles aujou...,Le système ne dispose pas de données en temps ...,[]

In [8]:
golden_path = os.path.join(
    PROJECT_PATH,
    "eval",
    "golden_draft.jsonl"
)

golden_questions.to_json(
    golden_path,
    orient="records",
    lines=True,
    force_ascii=False
)

print("Sauvegardé :", golden_path)

Sauvegardé : /content/drive/MyDrive/Assistant_HLM_RAG/eval/golden_draft.jsonl

In [9]:
with open(golden_path, "r", encoding="utf-8") as f:
    print(f.read())

{"id":"q001","type":"rag","question":"Comment déposer une demande de logement social ?","answer":"","gold_docs":[]}
{"id":"q002","type":"rag","question":"Qu'est-ce que le droit au logement opposable (DALO) ?","answer":"","gold_docs":[]}
{"id":"q003","type":"eligibility","question":"Avec 28 000 euros de revenus pour un couple avec un enfant à Lyon, suis-je éligible à un logement social ?","answer":"","gold_docs":[]}
{"id":"q004","type":"rpls","question":"Combien de logements sociaux vacants y a-t-il à Créteil ?","answer":"","gold_docs":[]}
{"id":"q005","type":"out_of_scope","question":"Quels logements sociaux sont disponibles aujourd'hui à Créteil ?","answer":"Le système ne dispose pas de données en temps réel sur les logements disponibles.","gold_docs":[]}

| Type | Nombre approximatif |
|---|---:|
| Questions RAG Service-Public / LEGI | 15 |
| Éligibilité | 8 |
| RPLS | 5 |
| DVF | 3 |
| Hors corpus / impossibles | 3 |
| Prompt injection | 3 |
| Questions pièges / causalité | 3 |
| **Total** | **40** |

✅ Google Drive connecté

✅ dossiers créés

✅ environnement Python initialisé

✅ définition du projet

✅ liste des sources

✅ premier golden set

Importer les données

In [10]:
###import os
###import zipfile

ZIP_PATH = os.path.join(
    PROJECT_PATH,
    "data",
    "raw",
    "service_public",
    "vosdroits-latest.zip"
)

EXTRACT_PATH = os.path.join(
    PROJECT_PATH,
    "data",
    "raw",
    "service_public",
    "xml"
)

os.makedirs(EXTRACT_PATH, exist_ok=True)

with zipfile.ZipFile(ZIP_PATH, "r") as zip_ref:
    zip_ref.extractall(EXTRACT_PATH)

print("Extraction terminée.")

KeyboardInterrupt:

In [11]:
import os
import zipfile
from pathlib import Path

ZIP_PATH = os.path.join(
    PROJECT_PATH,
    "data",
    "raw",
    "service_public",
    "vosdroits-latest.zip"
)

# Dossier LOCAL dans Colab
EXTRACT_PATH = "/content/service_public_xml"

os.makedirs(EXTRACT_PATH, exist_ok=True)

with zipfile.ZipFile(ZIP_PATH, "r") as zip_ref:
    zip_ref.extractall(EXTRACT_PATH)

print("Extraction terminée.")

xml_files = list(Path(EXTRACT_PATH).glob("*.xml"))

print("Nombre de fichiers XML :", len(xml_files))
print(xml_files[:5])

Extraction terminée.
Nombre de fichiers XML : 5574
[PosixPath('/content/service_public_xml/F2859.xml'), PosixPath('/content/service_public_xml/F39103.xml'), PosixPath('/content/service_public_xml/F39254.xml'), PosixPath('/content/service_public_xml/R58676.xml'), PosixPath('/content/service_public_xml/R60100.xml')]

In [12]:
from pathlib import Path

xml_files = list(Path(EXTRACT_PATH).glob("*.xml"))

print("Nombre total de fichiers XML :", len(xml_files))
print(xml_files[:10])

Nombre total de fichiers XML : 5574
[PosixPath('/content/service_public_xml/F2859.xml'), PosixPath('/content/service_public_xml/F39103.xml'), PosixPath('/content/service_public_xml/F39254.xml'), PosixPath('/content/service_public_xml/R58676.xml'), PosixPath('/content/service_public_xml/R60100.xml'), PosixPath('/content/service_public_xml/F16542.xml'), PosixPath('/content/service_public_xml/R60029.xml'), PosixPath('/content/service_public_xml/F583.xml'), PosixPath('/content/service_public_xml/R65687.xml'), PosixPath('/content/service_public_xml/F2428.xml')]

<Publication ID="F34779"
             spUrl="https://www.service-public.gouv.fr/particuliers/vosdroits/F34779">

    <dc:title>...</dc:title>

    <dc:subject>
        Papiers - Citoyenneté - Élections
    </dc:subject>

    <dc:description>...</dc:description>

    <dc:identifier>F34779</dc:identifier>

    <Theme>
        <Titre>...</Titre>
    </Theme>

    <Introduction>
        ...
    </Introduction>

    ...
</Publication>

In [13]:
import xml.etree.ElementTree as ET
import pandas as pd
from pathlib import Path

records = []

for file in Path(EXTRACT_PATH).glob("F*.xml"):
    try:
        tree = ET.parse(file)
        root = tree.getroot()

        ns = {
            "dc": "http://purl.org/dc/elements/1.1/"
        }

        doc_id = root.attrib.get("ID")
        url = root.attrib.get("spUrl")
        doc_type = root.attrib.get("type")
        last_major_update = root.attrib.get(
            "dateDerniereModificationImportante"
        )

        title_elem = root.find("dc:title", ns)
        subject_elem = root.find("dc:subject", ns)
        desc_elem = root.find("dc:description", ns)
        date_elem = root.find("dc:date", ns)

        title = (
            title_elem.text.strip()
            if title_elem is not None and title_elem.text
            else None
        )

        subject = (
            subject_elem.text.strip()
            if subject_elem is not None and subject_elem.text
            else None
        )

        description = (
            desc_elem.text.strip()
            if desc_elem is not None and desc_elem.text
            else None
        )

        date = (
            date_elem.text.strip()
            if date_elem is not None and date_elem.text
            else None
        )

        records.append({
            "document_id": doc_id,
            "title": title,
            "subject": subject,
            "description": description,
            "type": doc_type,
            "date": date,
            "last_major_update": last_major_update,
            "url": url,
            "file": str(file)
        })

    except Exception as e:
        print("Erreur :", file, e)

# **Vérifier** les thèmes disponibles *texte en italique*

In [14]:
df_service_public = pd.DataFrame(records)

print(df_service_public.shape)
df_service_public.head()

(3004, 9)

,document_id,title,subject,description,type,date,last_major_update,url,file
0,F2859,Comment la journée de solidarité est-elle acco...,Travail - Formation,La journée de solidarité prend la forme d'une ...,Fiche Question-réponse conditionnée,modified 2025-10-20,2023-01-01T00:00:00,https://www.service-public.gouv.fr/particulier...,/content/service_public_xml/F2859.xml
1,F39103,Qu'est-ce qu'un véhicule terrestre à moteur ?,Argent - Impôts - Consommation,Un véhicule terrestre à moteur (VTM) est un en...,Fiche Question-réponse conditionnée,modified 2025-05-28,None,https://www.service-public.gouv.fr/particulier...,/content/service_public_xml/F39103.xml
2,F39254,Dispositifs de pré-enregistrement du système e...,Étranger - Europe,Un dispositif de pré-enregistrement de type ki...,Fiche Question-réponse conditionnée,modified 2026-04-10,None,https://www.service-public.gouv.fr/particulier...,/content/service_public_xml/F39254.xml
3,F16542,Qu'est-ce que le certificat provisoire d'immat...,Transports - Mobilité,Un certificat provisoire d’immatriculation (CP...,Fiche Question-réponse conditionnée,modified 2026-01-01,2026-01-01T00:00:00,https://www.service-public.gouv.fr/particulier...,/content/service_public_xml/F16542.xml
4,F583,Congé de paternité et d'accueil de l'enfant da...,Travail - Formation,"L’agent public, second parent d'un enfant (pèr...",Fiche d'information conditionnée,modified 2026-06-01,2026-06-01T00:00:00,https://www.service-public.gouv.fr/particulier...,/content/service_public_xml/F583.xml

In [15]:
logement_subjects = df_service_public[
    df_service_public["subject"]
    .fillna("")
    .str.contains("logement", case=False)
]

print(logement_subjects.shape)

logement_subjects[
    ["document_id", "title", "subject"]
].head(50)

(350, 9)

,document_id,title,subject
8,F39743,Vente en l’état futur d’achèvement (Vefa),Logement
9,F282,Peut-on acheter son logement social ?,Logement
16,F1550,Quel mandat de vente peut-on confier à un agen...,Logement
21,F36762,Quelle autorisation d'urbanisme déposer pour c...,Logement
28,F38659,Pays Basque : montant du loyer pour un bail d'...,Logement
36,F640,Ravalement de façade d'un immeuble : à quelle ...,Logement
48,F31601,Peut-on conserver son logement social en cas d...,Logement
60,F31858,Peut-on brûler des déchets verts (végétaux) da...,Logement
62,F33173,Aide au logement : qu'est-ce que l'aide Mobili...,Logement
78,F36956,Peut-on reconstruire un bâtiment après sa dest...,Logement
104,F2066,Bail d’habitation : documents remis par le pro...,Logement
120,F34396,Paiement du loyer d'un logement du secteur pri...,Logement
123,F36492,[Amende pour abandon de déchets dans la rue],Logement
125,F13723,Indice de référence des loyers (IRL),Logement
127,F10007,Faire une demande de logement social (HLM),Logement
129,F37504,Diagnostic de performance énergétique collecti...,Logement
132,F31835,Local à poubelles d'un immeuble en copropriété...,Logement
135,F1703,Peut-on se rétracter après avoir signé un bail...,Logement
143,F11384,Qui peut assister aux réunions du conseil synd...,Logement
175,F34905,Quelle est la hauteur et la surface minimum d'...,Logement
182,F35254,Que faire quand des squatteurs occupent un log...,Logement
194,F37924,Quelles sont les règles d’urbanisme à respecte...,Logement
200,F34661,Colocation : quelles sont les règles ?,Logement
201,F31513,Copropriété : travaux et aménagements dans l'a...,Logement
205,F36766,Quelle autorisation d'urbanisme faut-il dépose...,Logement
212,F920,Rédaction du bail d'habitation (contrat de loc...,Logement
240,F39367,Droits des personnes expropriées,Logement
256,F1334,Quelle aide apporte le Fonds de solidarité pou...,Logement
275,F32061,Que doit indiquer l'annonce d'une vente immobi...,Logement
280,F3150,Diagnostic termites et autres insectes xylophages,Logement
293,F19069,Peut-on revendre son logement avant d'avoir re...,Logement
294,F32573,Sécurité incendie dans les immeubles en coprop...,Logement
308,F36490,[Obtenir de l'électricité avec des panneaux so...,Logement
319,F2484,Quelles sont les obligations du vendeur d'un t...,Logement
325,F2137,Quelles sont les règles de vote en assemblée g...,Logement
337,F17669,Permis de démolir,"Logement, Secteurs d'activité"
345,F1857,Le locataire doit-il accorder un droit de visi...,Logement
355,F31044,Le propriétaire d’un logement conventionné Ana...,Logement
360,F2667,Copropriété en difficulté : état de carence,Logement
371,F2559,Logement social : le bailleur peut-il résilier...,Logement
374,F2643,Copropriété en difficulté : intervention d'un ...,Logement
383,F31864,Quelles sont les différences entre les aides p...,Logement
390,F33298,Dans quel cas le débroussaillement est-il obli...,Logement
394,F35451,Tantièmes de copropriété : de quoi s'agit-il ?,Logement
395,F1220,Un mineur peut-il signer un bail d'habitation ?,Logement
402,F35977,Surface minimum d'un logement à louer,Logement
405,F2606,Syndicat des copropriétaires,Logement
406,F37827,MaPrimeRénov' Copropriété,Logement
460,F32059,Diagnostic technique global (DTG) de la coprop...,Logement
463,F2693,Le bail (ou contrat de location) peut-il inter...,Logement

# ***Puis rechercher spécifiquement le logement social***

In [16]:
df_service_public["search_text"] = (
    df_service_public["title"].fillna("")
    + " "
    + df_service_public["description"].fillna("")
    + " "
    + df_service_public["subject"].fillna("")
)

In [17]:
keywords = [
    "logement social",
    "HLM",
    "habitation à loyer modéré",
    "DALO",
    "droit au logement opposable",
    "demande de logement social",
    "surloyer",
    "supplément de loyer de solidarité",
    "APL",
    "aide personnalisée au logement"
]

pattern = "|".join(keywords)

df_hlm_candidates = df_service_public[
    df_service_public["search_text"]
    .str.contains(pattern, case=False, regex=True)
].copy()

print("Nombre de fiches candidates :", len(df_hlm_candidates))

Nombre de fiches candidates : 24

In [18]:
df_hlm_candidates[
    ["document_id", "title", "subject", "description"]
].sort_values("title")

,document_id,title,subject,description
1544,F12006,Aide personnalisée au logement (APL),Logement,"L'APL peut être versée, sous certaines conditi..."
2552,F1280,Allocation de logement sociale (ALS),Logement,L'ALS est attribuée sous conditions. L'ALS est...
2787,F37237,Dalo,Logement,Dalo
1723,F18005,Droit au logement opposable (Dalo) : faire val...,Logement,En cas de demande de logement social restée in...
733,F35683,Faire une demande de logement social,Logement,Faire une demande de logement social
127,F10007,Faire une demande de logement social (HLM),Logement,"Pour obtenir un logement social, vous devez fa..."
176,F35381,L'activité partielle de longue durée (APLD) ex...,"Social - Santé, Ressources humaines",L'activité partielle de longue durée (APLD) pe...
1285,F32037,"L'aide personnelle au logement (APL, ALF ou AL...",Logement,"En cas de loyers impayés, l'aide personnelle a..."
371,F2559,Logement social : le bailleur peut-il résilier...,Logement,Le bailleur social peut résilier le bail du lo...
2301,F21051,Logement social : supplément de loyer de solid...,Logement,Un surloyer est réclamé quand les revenus des ...
1216,F1170,Logement social : y a t-il transfert de bail e...,Logement,Lorsque la personne qui a signé le bail décède...
866,F31290,Logement social ou logement privé : quelles di...,Logement,Les principales différences concernent les con...
2425,F1317,Loyer d'un logement social,Logement,Le locataire d'un logement social peut avoir d...
347,F38004,L’activité partielle de longue durée (APLD) « ...,"Social - Santé, Ressources humaines",L'activité partielle de longue durée (APLD) re...
9,F282,Peut-on acheter son logement social ?,Logement,"Oui, le locataire peut acheter le logement soc..."
48,F31601,Peut-on conserver son logement social en cas d...,Logement,Sous certaines conditions liées à la hausse de...
1591,F1239,Peut-on échanger son logement social (HLM) ent...,Logement,L'échange de logement entre locataires du sect...
2007,F869,Quelles sont les conditions pour obtenir un lo...,Logement,"Pour obtenir un logement social, il faut respe..."
383,F31864,Quelles sont les différences entre les aides p...,Logement,Il existe 3 types d'aides personnelles au loge...
995,F32881,Radiation d'une demande de logement social,Logement,Une demande de logement peut être radiée juste...
2483,F32880,Renouvellement d'une demande de logement social,Logement,Une demande de logement social doit être renou...
913,F35010,S'informer sur la demande de logement social,Logement,S'informer sur la demande de logement social
2512,F32384,"Un locataire peut-il bénéficier de l'APL, l'AL...",Logement,Tout dépend du lien de parenté qui vous avez a...
2011,F1563,Un étudiant peut-il bénéficier d'une aide au l...,Logement,"Oui, un étudiant peut bénéficier (sous conditi..."

Étape suivante : extraire le texte complet

In [19]:
# 1
df_service_public.shape

(3004, 10)

In [20]:
# 2
df_service_public["subject"].value_counts()

subject
Travail - Formation                                                                        561
Argent - Impôts - Consommation                                                             383
Famille - Scolarité                                                                        374
Logement                                                                                   333
Social - Santé                                                                             254
Justice                                                                                    232
Transports - Mobilité                                                                      213
Papiers - Citoyenneté - Élections                                                          197
Étranger - Europe                                                                          170
Associations, fondations et fonds de dotation                                               82
Loisirs - Sports - Culture                                                                  68
Travail - Formation, Ressources humaines                                                    59
Logement, Secteurs d'activité                                                               13
Social - Santé, Ressources humaines                                                          5
Social - Santé, Financement                                                                  4
Argent - Impôts - Consommation, Secteurs d'activité                                          3
Étranger - Europe, Ressources humaines                                                       3
Argent - Impôts - Consommation, Pratiques commerciales                                       3
Argent - Impôts - Consommation, Ressources humaines                                          2
Logement, Fiscalité                                                                          2
Argent - Impôts - Consommation, Fiscalité                                                    2
Loisirs - Sports - Culture, Secteurs d'activité                                              2
Justice, Associations, fondations et fonds de dotation                                       1
Famille - Scolarité, Associations, fondations et fonds de dotation                           1
Famille - Scolarité, Étapes de vie                                                           1
Associations, fondations et fonds de dotation, Secteurs d'activité                           1
Argent - Impôts - Consommation, Comptabilité - Facturation                                   1
Travail - Formation, Associations, fondations et fonds de dotation, Ressources humaines      1
Transports - Mobilité, Secteurs d'activité                                                   1
Famille - Scolarité, Justice                                                                 1
Papiers - Citoyenneté - Élections, Associations, fondations et fonds de dotation             1
Logement, Secteurs d'activité, Environnement                                                 1
Travail - Formation, Papiers - Citoyenneté - Élections                                       1
Associations, fondations et fonds de dotation, Ressources humaines                           1
Argent - Impôts - Consommation, Logement                                                     1
Associations, fondations et fonds de dotation, Étapes de vie                                 1
Name: count, dtype: int64

In [21]:
# 3
logement_subjects[
    ["document_id", "title", "subject"]
].head(50)

,document_id,title,subject
8,F39743,Vente en l’état futur d’achèvement (Vefa),Logement
9,F282,Peut-on acheter son logement social ?,Logement
16,F1550,Quel mandat de vente peut-on confier à un agen...,Logement
21,F36762,Quelle autorisation d'urbanisme déposer pour c...,Logement
28,F38659,Pays Basque : montant du loyer pour un bail d'...,Logement
36,F640,Ravalement de façade d'un immeuble : à quelle ...,Logement
48,F31601,Peut-on conserver son logement social en cas d...,Logement
60,F31858,Peut-on brûler des déchets verts (végétaux) da...,Logement
62,F33173,Aide au logement : qu'est-ce que l'aide Mobili...,Logement
78,F36956,Peut-on reconstruire un bâtiment après sa dest...,Logement
104,F2066,Bail d’habitation : documents remis par le pro...,Logement
120,F34396,Paiement du loyer d'un logement du secteur pri...,Logement
123,F36492,[Amende pour abandon de déchets dans la rue],Logement
125,F13723,Indice de référence des loyers (IRL),Logement
127,F10007,Faire une demande de logement social (HLM),Logement
129,F37504,Diagnostic de performance énergétique collecti...,Logement
132,F31835,Local à poubelles d'un immeuble en copropriété...,Logement
135,F1703,Peut-on se rétracter après avoir signé un bail...,Logement
143,F11384,Qui peut assister aux réunions du conseil synd...,Logement
175,F34905,Quelle est la hauteur et la surface minimum d'...,Logement
182,F35254,Que faire quand des squatteurs occupent un log...,Logement
194,F37924,Quelles sont les règles d’urbanisme à respecte...,Logement
200,F34661,Colocation : quelles sont les règles ?,Logement
201,F31513,Copropriété : travaux et aménagements dans l'a...,Logement
205,F36766,Quelle autorisation d'urbanisme faut-il dépose...,Logement
212,F920,Rédaction du bail d'habitation (contrat de loc...,Logement
240,F39367,Droits des personnes expropriées,Logement
256,F1334,Quelle aide apporte le Fonds de solidarité pou...,Logement
275,F32061,Que doit indiquer l'annonce d'une vente immobi...,Logement
280,F3150,Diagnostic termites et autres insectes xylophages,Logement
293,F19069,Peut-on revendre son logement avant d'avoir re...,Logement
294,F32573,Sécurité incendie dans les immeubles en coprop...,Logement
308,F36490,[Obtenir de l'électricité avec des panneaux so...,Logement
319,F2484,Quelles sont les obligations du vendeur d'un t...,Logement
325,F2137,Quelles sont les règles de vote en assemblée g...,Logement
337,F17669,Permis de démolir,"Logement, Secteurs d'activité"
345,F1857,Le locataire doit-il accorder un droit de visi...,Logement
355,F31044,Le propriétaire d’un logement conventionné Ana...,Logement
360,F2667,Copropriété en difficulté : état de carence,Logement
371,F2559,Logement social : le bailleur peut-il résilier...,Logement
374,F2643,Copropriété en difficulté : intervention d'un ...,Logement
383,F31864,Quelles sont les différences entre les aides p...,Logement
390,F33298,Dans quel cas le débroussaillement est-il obli...,Logement
394,F35451,Tantièmes de copropriété : de quoi s'agit-il ?,Logement
395,F1220,Un mineur peut-il signer un bail d'habitation ?,Logement
402,F35977,Surface minimum d'un logement à louer,Logement
405,F2606,Syndicat des copropriétaires,Logement
406,F37827,MaPrimeRénov' Copropriété,Logement
460,F32059,Diagnostic technique global (DTG) de la coprop...,Logement
463,F2693,Le bail (ou contrat de location) peut-il inter...,Logement

In [22]:
# 4
print("Nombre de fiches HLM candidates :", len(df_hlm_candidates))

df_hlm_candidates[
    ["document_id", "title", "subject"]
].sort_values("title")

Nombre de fiches HLM candidates : 24

,document_id,title,subject
1544,F12006,Aide personnalisée au logement (APL),Logement
2552,F1280,Allocation de logement sociale (ALS),Logement
2787,F37237,Dalo,Logement
1723,F18005,Droit au logement opposable (Dalo) : faire val...,Logement
733,F35683,Faire une demande de logement social,Logement
127,F10007,Faire une demande de logement social (HLM),Logement
176,F35381,L'activité partielle de longue durée (APLD) ex...,"Social - Santé, Ressources humaines"
1285,F32037,"L'aide personnelle au logement (APL, ALF ou AL...",Logement
371,F2559,Logement social : le bailleur peut-il résilier...,Logement
2301,F21051,Logement social : supplément de loyer de solid...,Logement
1216,F1170,Logement social : y a t-il transfert de bail e...,Logement
866,F31290,Logement social ou logement privé : quelles di...,Logement
2425,F1317,Loyer d'un logement social,Logement
347,F38004,L’activité partielle de longue durée (APLD) « ...,"Social - Santé, Ressources humaines"
9,F282,Peut-on acheter son logement social ?,Logement
48,F31601,Peut-on conserver son logement social en cas d...,Logement
1591,F1239,Peut-on échanger son logement social (HLM) ent...,Logement
2007,F869,Quelles sont les conditions pour obtenir un lo...,Logement
383,F31864,Quelles sont les différences entre les aides p...,Logement
995,F32881,Radiation d'une demande de logement social,Logement
2483,F32880,Renouvellement d'une demande de logement social,Logement
913,F35010,S'informer sur la demande de logement social,Logement
2512,F32384,"Un locataire peut-il bénéficier de l'APL, l'AL...",Logement
2011,F1563,Un étudiant peut-il bénéficier d'une aide au l...,Logement

In [23]:
df_logement = df_service_public[
    df_service_public["subject"]
    .fillna("")
    .str.contains("Logement", case=False)
].copy()

print("Nombre total de fiches du thème Logement :", len(df_logement))

df_logement[
    ["document_id", "title", "subject"]
].sort_values("title")

Nombre total de fiches du thème Logement : 350

     document_id                                              title   subject
1250      F37190                 Achat d'un logement en copropriété  Logement
2693       F2762  Achat ou vente en viager : quelles sont les rè...  Logement
2497       F2961  Acte de vente d'un logement en l'état futur d'...  Logement
1686       F2962               Acte de vente d'un logement existant  Logement
1850      F12702  Acte de vente d'un terrain situé dans un lotis...  Logement
...          ...                                                ...       ...
1980      F32058   À quoi sert l'immatriculation des copropriétés ?  Logement
1427      F19905                     Éco-prêt à taux zéro (éco-PTZ)  Logement
1862      F38064        Éco-prêt à taux zéro (éco-PTZ) Copropriétés  Logement
2714      F31270  État des lieux d'entrée dans un bail d'habitation  Logement
1915      F33671  État des lieux de sortie pour un bail d'habita...  Logement

[350 rows x 3 columns]

In [24]:
pd.set_option("display.max_rows", None)

df_logement[
    ["document_id", "title"]
].sort_values("title")

     document_id                                              title
1250      F37190                 Achat d'un logement en copropriété
2693       F2762  Achat ou vente en viager : quelles sont les rè...
2497       F2961  Acte de vente d'un logement en l'état futur d'...
1686       F2962               Acte de vente d'un logement existant
1850      F12702  Acte de vente d'un terrain situé dans un lotis...
2606        F258           Acte de vente d'un terrain à bâtir isolé
2366       F1988  Affichage de l'autorisation d'urbanisme sur le...
62        F33173  Aide au logement : qu'est-ce que l'aide Mobili...
1884      F39682  Aide au retrait-gonflement des argiles (RGA) p...
1357       F1702  Aide aux travaux d'insonorisation d'un logemen...
1544      F12006               Aide personnalisée au logement (APL)
2815       F1328  Aides financières de l'Anah pour réaliser des ...
947       F13132             Allocation de logement familiale (ALF)
2552       F1280               Allocation de logement sociale (ALS)
1978      F10538  Ascenseur : sécurité, entretien et contrôle te...
1532        F447          Assainissement des eaux usées domestiques
1749       F2032                    Assurance dommages-ouvrage (DO)
2659      F37110  Audit énergétique en cas de vente d'un bien im...
1671       F1311  Augmentation et révision du loyer en cours de ...
2936      F18490  Avance Loca-Pass : aide au locataire pour le d...
2342      F31699  Bail d'habitation : travaux à la charge du pro...
104        F2066  Bail d’habitation : documents remis par le pro...
2945      F34769  Bail d’habitation : qu'est-ce qu'un logement m...
2706       F1165  Bail d’habitation : quelles différences entre ...
501       F36487  Bordeaux : montant du loyer pour un bail d'hab...
960        F3037                                Bornage de terrains
3002      F20586              Budget prévisionnel d'une copropriété
1619       F2665               Carnet d'entretien de la copropriété
602       F36759             Carnet d'information du logement (CIL)
1220      F31267  Caution du locataire ou du colocataire dans un...
1048       F1633                        Certificat d'urbanisme (CU)
2123      F35584             Certificats d'économie d'énergie (CEE)
2767       F2590                             Charges de copropriété
2515        F947  Charges à payer par le locataire (charges loca...
1032      F33667                                     Chèque énergie
2423       F1686       Clauses interdites dans un bail d'habitation
200       F34661             Colocation : quelles sont les règles ?
2930      F17709  Comment augmenter le loyer d'un logement soumi...
896       F32360  Comment calculer le délai de préavis en cas de...
2454       F1548  Comment changer de syndic de copropriété en fi...
2914      F18116  Comment choisir un fournisseur d'électricité o...
1517      F16832  Comment connaître le prix d'un logement ou d'u...
1017      F14226                    Comment consulter le cadastre ?
2065        F172  Comment déclarer un projet de puits ou de fora...
648       F32051    Comment est rémunéré le syndic de copropriété ?
2130      F39760  Comment faire lorsque la copropriété n’a plus ...
2901        F664  Comment obtenir des informations sur la qualit...
2338      F17759   Comment obtenir des renseignements immobiliers ?
787        F2125  Comment obtenir un arrêté d'alignement individ...
1670       F2127  Comment se procurer la copie d'un règlement de...
2829       F2416  Comment transformer un local professionnel ou ...
2782      F34401    Complément de loyer : quelles sont les règles ?
824        F2610                    Conseil syndical de copropriété
1733      F34554  Construire sa maison : quel contrat passer ave...
2804       F2963  Contrat de réservation d'un logement en vente ...
2330      F34825  Convention Anah : qu'apporte l'intermédiation ...
2286       F2615  Convocation de l'assemblée générale des coprop...
374        F2643  Copropriété en difficulté : intervention d'un ...
2939      F20388  Copropriété en difficulté : mesures préventive...
360        F2667        Copropriété en difficulté : état de carence
1334      F32088  Copropriété en graves difficultés : plan de sa...
1881      F14745  Copropriété : individualisation de la consomma...
201       F31513  Copropriété : travaux et aménagements dans l'a...
1228      F35202  Couple de concubins locataire de son logement ...
1267       F2562  Couple de concubins locataire de son logement ...
2903       F1159  Couple marié locataire de son logement : quell...
1863       F2565  Couple pacsé locataire de son logement : quell...
2134      F36622  Couple pacsé locataire de son logement : quell...
1958         F76  Création d'une ouverture ou d'un aménagement a...
2787      F37237                                               Dalo
786       F20568  Dans quel cas doit-on faire appel à un archite...
390       F33298  Dans quel cas le débroussaillement est-il obli...
2857       F1216  Dans quel cas saisir la commission département...
594       F35266  Diagnostic Bruit des aéroports (état des nuisa...
129       F37504  Diagnostic de performance énergétique collecti...
578       F31685  Diagnostic immobilier : assainissement des eau...
1281       F1142  Diagnostic immobilier : constat de risque d'ex...
1363      F16096  Diagnostic immobilier : diagnostic de performa...
1913        F742  Diagnostic immobilier : état d'amiante ou "dia...
2193      F18692  Diagnostic immobilier : état de l'installation...
2986      F17337  Diagnostic immobilier : état de l'installation...
2851      F12239           Diagnostic immobilier : état des risques
460       F32059  Diagnostic technique global (DTG) de la coprop...
280        F3150  Diagnostic termites et autres insectes xylophages
618       F17376  Diagnostics immobiliers : où trouver un diagno...
2919       F1722  Dispositif de sécurité des piscines privées fa...
2225      F33682  Doit-on obligatoirement entreprendre des trava...
802        F2443  Doit-on recevoir les eaux qui s'écoulent du te...
1723      F18005  Droit au logement opposable (Dalo) : faire val...
1632       F2040  Droit de passage sur le terrain d'un autre pro...
240       F39367                   Droits des personnes expropriées
967       F35212  Déchets d'équipements électriques et électroni...
1327      F31955  Déchets d'équipements électriques et électroni...
2466       F1997  Déclaration attestant l'achèvement et la confo...
2740       F1992          Déclaration d'ouverture de chantier (DOC)
1993      F17578                         Déclaration préalable (DP)
1296       F2103  Dégradations causées lors d'un cambriolage : q...
1708      F39713                                  Dépôt de garantie
634       F31269        Dépôt de garantie dans un bail d'habitation
2018       F2619  Déroulement d'une assemblée générale des copro...
1246      F19950  Détecteur de fumée : sécurité incendie dans le...
2557      F31418       Emprunt bancaire collectif d'une copropriété
465       F31672  En cas de changement de syndic, que deviennent...
529        F1314  En quoi consiste l'encadrement des loyers à re...
1955      F31954                   Encombrants (déchets volumineux)
2976      F20760  Entretien annuel de la chaudière : quelles règ...
2344      F31697  Entretien courant et réparations locatives à l...
1031      F36219  Est Ensemble : montant du loyer pour un bail d...
1837      F31963  Existe-il une amende pour abandon de déchets d...
733       F35683               Faire une demande de logement social
127       F10007         Faire une demande de logement social (HLM)
541       F15133  Faut-il déneiger le trottoir situé devant son ...
1969      F37294  Faut-il un état daté pour vendre un logement d...
1178      F36775  Faut-il une autorisation d'urbanisme pour amén...
1550      F37925  Faut-il une autorisation d'urbanisme pour cons...
2192      F37923  Faut-il une autorisation d'urbanisme pour cons...
2947      F36780  Faut-il une autorisation d'urbanisme pour inst...
1368      F31923  Faut-il une autorisation d'urbanisme pour pose...
1631      F36798  Faut-il une autorisation d'urbanisme pour pose...
2376      F37976  Faut-il une autorisation pour diviser un bâtim...
2991      F34051                Fiche synthétique de la copropriété
2854      F34026  Fonds de travaux mis en place dans les copropr...
2615        F375  Frais d'agence immobilière à la location d'un ...
829        F1169  Futur locataire d'un logement privé : justific...
1132      F33453  Garantie Visale : caution pour le locataire (i...
2506      F34253    Garantie de livraison d'une maison individuelle
1052       F2034               Garantie décennale des constructeurs
1276       F2958           Garanties après la réception des travaux
1219      F39137  Grenoble-Alpes Métropole : montant du loyer po...
2677        F288                     Habitat contenant de l'amiante
1582       F1141                         Habitat contenant du plomb
2964      F20599                         Habitat contenant du radon
1994      F16158             Habitat insalubre (ou habitat indigne)
2773      F16104                  Habitat menaçant ruine (en péril)
2807      F20055  Impayés de factures (gaz, électricité, eau, té...
2439      F39380            Indemnisation des personnes expropriées
125       F13723               Indice de référence des loyers (IRL)
2187        F642  Infractions aux règles d'urbanisme : quels son...
1846      F31404  Installation ou construction d'une piscine pri...
1285      F32037  L'aide personnelle au logement (APL, ALF ou AL...
804        F1557  La tarification sociale de l'eau est-elle touj...
1351       F2407  La vente d'un bien immobilier est-elle soumise...
463        F2693  Le bail (ou contrat de location) peut-il inter...
345        F1857  Le locataire doit-il accorder un droit de visi...
2686      F31629  Le locataire peut-il payer le dernier mois de ...
2313       F1626  Le propriétaire choisit-il librement le locata...
2969      F32001  Le propriétaire d'un logement loué peut-il le ...
355       F31044  Le propriétaire d’un logement conventionné Ana...
2228      F31522  Le propriétaire est-il responsable des nuisanc...
2111       F2889  Le propriétaire peut-il facturer des frais de ...
2041       F2122  Le salaire du concierge, gardien ou employé fa...
2479        F896  Le syndic peut-il imposer une avance de trésor...
2850      F34408  Lille, Hellemmes et Lomme : montant du loyer p...
1791       F2956  Livraison d'un logement vendu en état futur d'...
132       F31835  Local à poubelles d'un immeuble en copropriété...
2635      F35978                                    Logement décent
371        F2559  Logement social : le bailleur peut-il résilier...
2301      F21051  Logement social : supplément de loyer de solid...
1216       F1170  Logement social : y a t-il transfert de bail e...
866       F31290  Logement social ou logement privé : quelles di...
2082       F2042                            Logement à louer décent
1986       F1351  Logement à louer : dans quel cas signer une co...
933       F35323  Logement à louer : que doit indiquer l'annonce...
2426       F2541  Loyer d'un logement conventionné (Anah) : y a ...
2425       F1317                         Loyer d'un logement social
857        F1312  Loyer sous-évalué d'un logement : hausse au re...
2178      F31272           Loyers impayés et expulsion du locataire
622       F36218  Lyon et Villeurbanne : montant du loyer pour u...
2896      F37501  MaPrimeAdapt' : travaux d'adaptation du logeme...
1534      F35083                                MaPrimeRénov' (MPR)
406       F37827                          MaPrimeRénov' Copropriété
1957      F31473                        Maison : travaux extérieurs
2438      F14748  Micro-logement : doit-on payer une taxe en cas...
738       F19450        Modification d'une autorisation d'urbanisme
2383       F1310  Montant du loyer d'un logement appartenant à u...
1314      F36437  Montpellier : montant du loyer pour un bail d'...
2583       F2415                                        Mur mitoyen
2128      F20762          Médiateur de l'eau : comment y recourir ?
2085      F20820  Médiateur national de l'énergie : comment y re...
2161      F31300  Obligation du locataire : assurance habitation...
2761      F31487  Obtenir de l'électricité avec des panneaux sol...
2601      F31488  Obtenir de la chaleur à l'aide d'une installat...
2484      F16217                                  Ordures ménagères
120       F34396  Paiement du loyer d'un logement du secteur pri...
1633       F1214  Paiement du loyer par le locataire (bail d’hab...
2609      F34407  Paris : montant du loyer pour un bail d'habita...
1339      F31518  Partie commune réservée à l'usage exclusif d'u...
1485      F31512  Parties privatives réservées à l'usage exclusi...
28        F38659  Pays Basque : montant du loyer pour un bail d'...
2507      F17665                                  Permis d'aménager
2516       F1986                          Permis de construire (PC)
337       F17669                                  Permis de démolir
1414      F31527  Peut-on accrocher librement des objets aux fen...
9           F282              Peut-on acheter son logement social ?
60        F31858  Peut-on brûler des déchets verts (végétaux) da...
2387       F3107  Peut-on changer l'affectation d'un lot de copr...
48        F31601  Peut-on conserver son logement social en cas d...
2204        F924  Peut-on construire ou aménager un terrain en z...
872       F20567  Peut-on contester une autorisation d'urbanisme...
1387      F35288  Peut-on contester une décision prise en assemb...
2494      F31644  Peut-on créer un syndicat secondaire dans un g...
1793      F20554  Peut-on encore bénéficier de MaPrimeRénov' Sér...
2404      F37655  Peut-on encore bénéficier de la Prime « Coup d...
1609       F1613  Peut-on encore bénéficier des aides à l'adapta...
2402      F33663  Peut-on faire annuler une décision de préempti...
1922      F10696  Peut-on faire payer les frais d'état des lieux...
887       F15837  Peut-on forcer un propriétaire à insonoriser s...
2315      F34210  Peut-on mettre en location un logement dans un...
990       F31671  Peut-on mettre fin au mandat en cours d'un syn...
1165         F67  Peut-on passer sur le terrain de son voisin po...
78        F36956  Peut-on reconstruire un bâtiment après sa dest...
293       F19069  Peut-on revendre son logement avant d'avoir re...
135        F1703  Peut-on se rétracter après avoir signé un bail...
932         F620  Peut-on stationner une caravane ou installer u...
1591       F1239  Peut-on échanger son logement social (HLM) ent...
885       F35108                                            Piscine
1783      F35761  Plaine Commune : montant du loyer pour un bail...
528       F36760  Plan pluriannuel de travaux (PPT) mis en place...
2889        F614  Plantation de végétaux (haies, arbres, bambous...
1318      F34421                    Prime "Coup de pouce Chauffage"
2855      F35755  Prime Coup de pouce Rénovation d'ampleur des m...
874       F35779  Prime Coup de pouce Rénovation performante de ...
1383       F2636  Procès-verbal d'assemblée générale des copropr...
2328        F762                          Procédure d’expropriation
1981       F2965  Promesse de vente d'un logement existant : pro...
1067       F2057       Promesse de vente d'un terrain isolé à bâtir
2893      F16455  Promesse de vente d'un terrain situé dans un l...
1418       F1168  Préavis et formalités du congé donné par le lo...
2743        F929  Préavis et formalités du congé donné par le pr...
2801      F38425  Prêt avance mutation ne portant pas intérêt (é...
2633       F1616           Prêt à l'amélioration de l'habitat (PAH)
2331      F39003  Prêt à l'amélioration du lieu d'accueil (PALA)...
778       F10039  Qu'est-ce qu'un bail de sortie progressive de ...
1917       F1219  Qu'est-ce qu'un logement soumis à la loi de 19...
2262        F188  Qu'est-ce qu'une condition suspensive d'obtent...
1589       F2753  Qu'est-ce qu'une offre d'achat d'un bien immob...
1497      F33877  Qu'est-ce que le règlement intérieur de coprop...
1404      F34736              Quand s'applique la trêve hivernale ?
2973      F33664  Que devient le bail d'un locataire dont le log...
275       F32061  Que doit indiquer l'annonce d'une vente immobi...
779       F13737  Que faire en cas d'attroupement dans son immeu...
2289        F389  Que faire en cas d'augmentation anormale de sa...
931        F1176  Que faire en cas d'utilisation abusive d'un ba...
665       F31301  Que faire en cas de litige lié à la location d...
2281       F2618  Que faire lorsque l'on a perdu l'acte de propr...
182       F35254  Que faire quand des squatteurs occupent un log...
2433      F32305  Que faire quand le locataire abandonne le loge...
693        F1525  Que faire si le terrain d’un voisin n’est pas ...
2564        F289  Que risque le propriétaire d'un immeuble ou d'...
919        F2533  Quel contrat passer avec une entreprise pour d...
2746        F479  Quel est le délai de prescription d'une dette ...
2118      F32973  Quel est le tarif d’un huissier (à présent app...
16         F1550  Quel mandat de vente peut-on confier à un agen...
256        F1334  Quelle aide apporte le Fonds de solidarité pou...
21        F36762  Quelle autorisation d'urbanisme déposer pour c...
2234      F24612  Quelle autorisation d'urbanisme déposer pour c...
1315      F36768  Quelle autorisation d'urbanisme déposer pour c...
2396      F36767  Quelle autorisation d'urbanisme déposer pour f...
588       F36777  Quelle autorisation d'urbanisme déposer pour f...
2112        F662  Quelle autorisation d'urbanisme déposer pour i...
1757      F31471  Quelle autorisation d'urbanisme déposer pour i...
1785      F36773  Quelle autorisation d'urbanisme déposer pour i...
2133      F36774  Quelle autorisation d'urbanisme faut-il dépose...
646       F36778  Quelle autorisation d'urbanisme faut-il dépose...
205       F36766  Quelle autorisation d'urbanisme faut-il dépose...
728       F36779  Quelle autorisation d'urbanisme faut-il dépose...
1636      F37932  Quelle autorisation d'urbanisme faut-il pour d...
2147      F35336  Quelle autorisation déposer pour faire un chan...
1033      F36776  Quelle autorisation d’urbanisme déposer pour c...
175       F34905  Quelle est la hauteur et la surface minimum d'...
2159        F481  Quelle est la hauteur réglementaire d'un garde...
961       F31911  Quelles aides financières peut-on percevoir po...
1244      F34339  Quelles précautions prendre avant l'achat d'un...
2699      F33818  Quelles précautions prendre avant l'achat d'un...
2440      F36909  Quelles questions d'urbanisme se poser avant d...
2729      F31475  Quelles règles respecter pour installer un jac...
2482       F2073  Quelles sont les conditions de vente d’un terr...
2007        F869  Quelles sont les conditions pour obtenir un lo...
383       F31864  Quelles sont les différences entre les aides p...
319        F2484  Quelles sont les obligations du vendeur d'un t...
2834      F34759       Quelles sont les règles d'un bail mobilité ?
1545      F14747  Quelles sont les règles de location d'une plac...
971        F2315  Quelles sont les règles de location que le pro...
325        F2137  Quelles sont les règles de vote en assemblée g...
1736      F36961  Quelles sont les règles d’urbanisme à respecte...
194       F37924  Quelles sont les règles d’urbanisme à respecte...
1126       F3131  Quelles sont les règles pour construire ou ins...
1170      F33463  Quels sont les diagnostics immobiliers qu’un b...
1356      F10798  Quels sont les diagnostics immobiliers à fourn...
2931      F35742     Quels sont les travaux à déclarer aux impôts ?
1286      F31531  Qui est prioritaire pour acheter un bien dans ...
1646      F21105  Qui est responsable des dégradations dans un l...
2723      F32920  Qui paie les charges de copropriété l'année de...

In [25]:
print("Total Service-Public :", len(df_service_public))
print("Thème Logement :", len(df_logement))
print("Candidates HLM strict :", len(df_hlm_candidates))

Total Service-Public : 3004
Thème Logement : 350
Candidates HLM strict : 24

In [26]:
housing_keywords = [
    "logement",
    "HLM",
    "logement social",
    "location",
    "locataire",
    "bail",
    "loyer",
    "APL",
    "ALS",
    "ALF",
    "DALO",
    "surloyer",
    "supplément de loyer",
    "expulsion",
    "dépôt de garantie",
    "état des lieux",
    "charges locatives",
    "aide au logement",
    "bailleur",
    "habitation"
]

pattern_housing = "|".join(housing_keywords)

df_housing_candidates = df_service_public[
    df_service_public["search_text"]
    .str.contains(pattern_housing, case=False, regex=True)
].copy()

print("Nombre de fiches logement élargi :", len(df_housing_candidates))

Nombre de fiches logement élargi : 505

In [27]:
df_housing_candidates[
    ["document_id", "title", "subject"]
].sort_values("title")

,document_id,title,subject
2570,F35175,A t-on droit au PTZ quand on est déjà propriét...,Argent - Impôts - Consommation
762,F1529,A-t-on droit au PTZ quand on est déjà propriét...,Argent - Impôts - Consommation
1250,F37190,Achat d'un logement en copropriété,Logement
2693,F2762,Achat ou vente en viager : quelles sont les rè...,Logement
2497,F2961,Acte de vente d'un logement en l'état futur d'...,Logement
1686,F2962,Acte de vente d'un logement existant,Logement
1850,F12702,Acte de vente d'un terrain situé dans un lotis...,Logement
2606,F258,Acte de vente d'un terrain à bâtir isolé,Logement
2366,F1988,Affichage de l'autorisation d'urbanisme sur le...,Logement
62,F33173,Aide au logement : qu'est-ce que l'aide Mobili...,Logement
1884,F39682,Aide au retrait-gonflement des argiles (RGA) p...,Logement
1357,F1702,Aide aux travaux d'insonorisation d'un logemen...,Logement
1544,F12006,Aide personnalisée au logement (APL),Logement
20,F15252,Aide à la reprise ou à la création d'entrepris...,"Social - Santé, Financement"
2815,F1328,Aides financières de l'Anah pour réaliser des ...,Logement
186,F12242,Allocation aux adultes handicapés (AAH),Social - Santé
1689,F12386,Allocation chômage d'aide au retour à l'emploi...,Social - Santé
2546,F38882,Allocation chômage d'aide au retour à l'emploi...,Social - Santé
969,F14860,Allocation chômage d'aide au retour à l'emploi...,Social - Santé
1954,F38881,Allocation chômage d'aide au retour à l'emploi...,Social - Santé
2047,F291,Allocation d'aide au retour à l'emploi formati...,Social - Santé
1028,F31234,Allocation d'invalidité temporaire (AIT) dans ...,Social - Santé
1764,F14809,Allocation d'éducation de l'enfant handicapé (...,Social - Santé
1321,F31430,Allocation de base de la Paje en cas d'adoptio...,Famille - Scolarité
2573,F2552,Allocation de base de la Paje versée à la nais...,Famille - Scolarité
947,F13132,Allocation de logement familiale (ALF),Logement
2552,F1280,Allocation de logement sociale (ALS),Logement
2590,F1293,Allocation de reconnaissance du combattant (an...,Papiers - Citoyenneté - Élections
1237,F1878,Allocation de rentrée scolaire (ARS),Famille - Scolarité
2455,F16871,Allocation de solidarité aux personnes âgées (...,Social - Santé
2268,F12484,Allocation de solidarité spécifique (ASS),Social - Santé
1036,F33645,Allocation de soutien familial (ASF) : enfant ...,Famille - Scolarité
474,F33646,Allocation de soutien familial (ASF) : enfant ...,Famille - Scolarité
709,F33647,Allocation de soutien familial (ASF) : enfant ...,Famille - Scolarité
1890,F815,Allocation de soutien familial (ASF) : parents...,Famille - Scolarité
1947,F31688,Allocation de sécurisation professionnelle (ASP),Travail - Formation
1399,F706,Allocation journalière d'accompagnement d'une ...,Travail - Formation
2599,F15132,Allocation journalière de présence parentale (...,Famille - Scolarité
2673,F10009,Allocation personnalisée d'autonomie (Apa),Social - Santé
2957,F2572,Allocation simple d'aide sociale aux personnes...,Social - Santé
1560,F1024,Allocation spécifique annuelle pour étudiant e...,Famille - Scolarité
968,F16940,Allocation supplémentaire d'invalidité (Asi),Social - Santé
1333,F35558,Allocation versée en cas de décès d'un enfant,Famille - Scolarité
83,F744,Allocation veuvage,Famille - Scolarité
672,F2064,Allocations chômage : comment est calculé le s...,Social - Santé
1579,F13213,Allocations familiales (famille de 2 enfants o...,Famille - Scolarité
1563,F2112,Apa à domicile : son versement peut-il être su...,Social - Santé
69,F34092,Arnaques à la location immobilière sur internet,Justice
1978,F10538,"Ascenseur : sécurité, entretien et contrôle te...",Logement
1532,F447,Assainissement des eaux usées domestiques,Logement
727,F21925,Association cultuelle,"Associations, fondations et fonds de dotation"
992,F1218,Association de locataires,"Associations, fondations et fonds de dotation"
1749,F2032,Assurance dommages-ouvrage (DO),Logement
1084,F1350,Assurance du locataire : garanties complémenta...,Argent - Impôts - Consommation
900,F2023,Assurance du logement par le propriétaire,Argent - Impôts - Consommation
1537,F1352,Assurance dégâts des eaux,Argent - Impôts - Consommation
993,F2028,Assurance habitation et vol : conditions de pr...,Argent - Impôts - Consommation
1234,F3075,Assurance habitation : comment se déroule l'ex...,Argent - Impôts - Consommation
810,F10830,Assurance habitation : en cas d'achat ou de ve...,Argent - Impôts - Consommation
1362,F2123,Assurance habitation : qu'est-ce que la garant...,Argent - Impôts - Consommation
1106,F3050,Assurance habitation : recours en cas de litig...,Argent - Impôts - Consommation
2618,F21532,Assurance habitation : risque incendie ou expl...,Argent - Impôts - Consommation
988,F19083,Assurance habitation : résiliation du contrat,Argent - Impôts - Consommation
284,F2591,Assurance habitation : souscription du contrat,Argent - Impôts - Consommation
2659,F37110,Audit énergétique en cas de vente d'un bien im...,Logement
1671,F1311,Augmentation et révision du loyer en cours de ...,Logement
2936,F18490,Avance Loca-Pass : aide au locataire pour le d...,Logement
2342,F31699,Bail d'habitation : travaux à la charge du pro...,Logement
104,F2066,Bail d’habitation : documents remis par le pro...,Logement
2945,F34769,Bail d’habitation : qu'est-ce qu'un logement m...,Logement
2706,F1165,Bail d’habitation : quelles différences entre ...,Logement
501,F36487,Bordeaux : montant du loyer pour un bail d'hab...,Logement
960,F3037,Bornage de terrains,Logement
3002,F20586,Budget prévisionnel d'une copropriété,Logement
1619,F2665,Carnet d'entretien de la copropriété,Logement
602,F36759,Carnet d'information du logement (CIL),Logement
1220,F31267,Caution du locataire ou du colocataire dans un...,Logement
1048,F1633,Certificat d'urbanisme (CU),"Logement, Secteurs d'activité"
2123,F35584,Certificats d'économie d'énergie (CEE),Logement
1233,F34797,Changements dans l'administration d'une associ...,"Associations, fondations et fonds de dotation"
2767,F2590,Charges de copropriété,Logement
2515,F947,Charges à payer par le locataire (charges loca...,Logement
1032,F33667,Chèque énergie,Logement
2423,F1686,Clauses interdites dans un bail d'habitation,Logement
2005,F21478,Colocation et assurance habitation,Argent - Impôts - Consommation
200,F34661,Colocation : quelles sont les règles ?,Logement
2760,F21509,Comment assurer un échange de logement et la p...,Argent - Impôts - Consommation
2930,F17709,Comment augmenter le loyer d'un logement soumi...,Logement
896,F32360,Comment calculer le délai de préavis en cas de...,Logement
2454,F1548,Comment changer de syndic de copropriété en fi...,Logement
2914,F18116,Comment choisir un fournisseur d'électricité o...,Logement
1517,F16832,Comment connaître le prix d'un logement ou d'u...,Logement
1017,F14226,Comment consulter le cadastre ?,Logement
1819,F31912,Comment demander un logement étudiant au Crous ?,Famille - Scolarité
2065,F172,Comment déclarer un projet de puits ou de fora...,Logement
648,F32051,Comment est rémunéré le syndic de copropriété ?,Logement
2130,F39760,Comment faire lorsque la copropriété n’a plus ...,Logement
955,F31257,Comment fonctionne la franchise en matière d'a...,Argent - Impôts - Consommation
2901,F664,Comment obtenir des informations sur la qualit...,Logement
2338,F17759,Comment obtenir des renseignements immobiliers ?,Logement
1037,F33536,Comment obtenir la carte grise d'un véhicule e...,Transports - Mobilité
787,F2125,Comment obtenir un arrêté d'alignement individ...,Logement
1201,F31686,Comment payer ses impôts locaux ?,Argent - Impôts - Consommation
1670,F2127,Comment se procurer la copie d'un règlement de...,Logement
2829,F2416,Comment transformer un local professionnel ou ...,Logement
2782,F34401,Complément de loyer : quelles sont les règles ?,Logement
1734,F16136,Compte épargne logement (CEL),Argent - Impôts - Consommation
824,F2610,Conseil syndical de copropriété,Logement
1733,F34554,Construire sa maison : quel contrat passer ave...,Logement
2804,F2963,Contrat de réservation d'un logement en vente ...,Logement
2330,F34825,Convention Anah : qu'apporte l'intermédiation ...,Logement
2286,F2615,Convocation de l'assemblée générale des coprop...,Logement
374,F2643,Copropriété en difficulté : intervention d'un ...,Logement
2939,F20388,Copropriété en difficulté : mesures préventive...,Logement
360,F2667,Copropriété en difficulté : état de carence,Logement
1334,F32088,Copropriété en graves difficultés : plan de sa...,Logement
1881,F14745,Copropriété : individualisation de la consomma...,Logement
201,F31513,Copropriété : travaux et aménagements dans l'a...,Logement
1228,F35202,Couple de concubins locataire de son logement ...,Logement
1267,F2562,Couple de concubins locataire de son logement ...,Logement
2903,F1159,Couple marié locataire de son logement : quell...,Logement
1863,F2565,Couple pacsé locataire de son logement : quell...,Logement
2134,F36622,Couple pacsé locataire de son logement : quell...,Logement
1958,F76,Création d'une ouverture ou d'un aménagement a...,Logement
2726,F12216,DSE (dossier social étudiant) : comment demand...,Famille - Scolarité
2787,F37237,Dalo,Logement
786,F20568,Dans quel cas doit-on faire appel à un archite...,"Logement, Secteurs d'activité"
390,F33298,Dans quel cas le débroussaillement est-il obli...,Logement
2857,F1216,Dans quel cas saisir la commission département...,Logement
2398,F20199,Dans quels cas un enfant peut-il être considér...,Social - Santé
594,F35266,Diagnostic Bruit des aéroports (état des nuisa...,Logement
129,F37504,Diagnostic de performance énergétique collecti...,Logement
578,F31685,Diagnostic immobilier : assainissement des eau...,Logement
1281,F1142,Diagnostic immobilier : constat de risque d'ex...,Logement
1363,F16096,Diagnostic immobilier : diagnostic de performa...,Logement
1913,F742,"Diagnostic immobilier : état d'amiante ou ""dia...",Logement
2193,F18692,Diagnostic immobilier : état de l'installation...,Logement
2986,F17337,Diagnostic immobilier : état de l'installation...,Logement
2851,F12239,Diagnostic immobilier : état des risques,Logement
460,F32059,Diagnostic technique global (DTG) de la coprop...,Logement
280,F3150,Diagnostic termites et autres insectes xylophages,Logement
618,F17376,Diagnostics immobiliers : où trouver un diagno...,Logement
1295,F14750,Discrimination à la location d’un logement,Justice
2919,F1722,Dispositif de sécurité des piscines privées fa...,Logement
1003,F31329,Doit-on assurer une voiture en leasing (ou cré...,Argent - Impôts - Consommation
2225,F33682,Doit-on obligatoirement entreprendre des trava...,Logement
802,F2443,Doit-on recevoir les eaux qui s'écoulent du te...,Logement
2789,F34102,Doit-on verser des cotisations sociales pour l...,Argent - Impôts - Consommation
1723,F18005,Droit au logement opposable (Dalo) : faire val...,Logement
1632,F2040,Droit de passage sur le terrain d'un autre pro...,Logement
240,F39367,Droits des personnes expropriées,Logement
1908,F32454,"Droits du demandeur d'asile : soins, logement,...",Étranger - Europe
2121,F19134,Durée de conservation des papiers,Papiers - Citoyenneté - Élections
967,F35212,Déchets d'équipements électriques et électroni...,Logement
1327,F31955,Déchets d'équipements électriques et électroni...,Logement
2466,F1997,Déclaration attestant l'achèvement et la confo...,"Logement, Secteurs d'activité"
2740,F1992,Déclaration d'ouverture de chantier (DOC),"Logement, Secteurs d'activité"
2183,F1119,Déclaration initiale d'une association,"Associations, fondations et fonds de dotation"
1993,F17578,Déclaration préalable (DP),"Logement, Secteurs d'activité"
1296,F2103,Dégradations causées lors d'un cambriolage : q...,Logement
1245,F10827,Déménagement du locataire : quelle incidence s...,Argent - Impôts - Consommation
1708,F39713,Dépôt de garantie,Logement
634,F31269,Dépôt de garantie dans un bail d'habitation,Logement
2018,F2619,Déroulement d'une assemblée générale des copro...,Logement
1246,F19950,Détecteur de fumée : sécurité incendie dans le...,Logement
1302,F1026,Effets d'un Pacs,Famille - Scolarité
2557,F31418,Emprunt bancaire collectif d'une copropriété,Logement
465,F31672,"En cas de changement de syndic, que deviennent...",Logement
1349,F15293,"En cas de décès d'un demandeur d'emploi, qui p...",Social - Santé
1811,F33314,En quoi consiste l'allocation pour demandeur d...,Étranger - Europe
529,F1314,En quoi consiste l'encadrement des loyers à re...,Logement
1955,F31954,Encombrants (déchets volumineux),Logement
2976,F20760,Entretien annuel de la chaudière : quelles règ...,Logement
2344,F31697,Entretien courant et réparations locatives à l...,Logement
1031,F36219,Est Ensemble : montant du loyer pour un bail d...,Logement
2205,F13517,Européen en France : refus d'entrée et éloigne...,Étranger - Europe
1837,F31963,Existe-il une amende pour abandon de déchets d...,Logement
1916,F11891,Expulsion d'un étranger hors de France,Étranger - Europe
855,F33175,Faire de sa résidence principale une location ...,Loisirs - Sports - Culture
1972,F2043,Faire de sa résidence secondaire une location ...,Loisirs - Sports - Culture
733,F35683,Faire une demande de logement social,Logement
127,F10007,Faire une demande de logement social (HLM),Logement
541,F15133,Faut-il déneiger le trottoir situé devant son ...,Logement
1969,F37294,Faut-il un état daté pour vendre un logement d...,Logement
1178,F36775,Faut-il une autorisation d'urbanisme pour amén...,Logement
1550,F37925,Faut-il une autorisation d'urbanisme pour cons...,Logement
2192,F37923,Faut-il une autorisation d'urbanisme pour cons...,Logement
2947,F36780,Faut-il une autorisation d'urbanisme pour inst...,Logement
1368,F31923,Faut-il une autorisation d'urbanisme pour pose...,"Logement, Secteurs d'activité, Environnement"
1631,F36798,Faut-il une autorisation d'urbanisme pour pose...,Logement
2376,F37976,Faut-il une autorisation pour diviser un bâtim...,Logement
2991,F34051,Fiche synthétique de la copropriété,Logement
2854,F34026,Fonds de travaux mis en place dans les copropr...,Logement
845,F17912,Foyer de travailleurs migrants (FTM),Social - Santé
2615,F375,Frais d'agence immobilière à la location d'un ...,Logement
829,F1169,Futur locataire d'un logement privé : justific...,Logement
1132,F33453,Garantie Visale : caution pour le locataire (i...,Logement
2506,F34253,Garantie de livraison d'une maison individuelle,Logement
1052,F2034,Garantie décennale des constructeurs,"Logement, Secteurs d'activité"
1276,F2958,Garanties après la réception des travaux,Logement
1219,F39137,Grenoble-Alpes Métropole : montant du loyer po...,Logement
1514,F1928,Guichet unique du spectacle occasionnel (Guso),"Associations, fondations et fonds de dotation,..."
2677,F288,Habitat contenant de l'amiante,Logement
1582,F1141,Habitat contenant du plomb,Logement
2964,F20599,Habitat contenant du radon,Logement
1994,F16158,Habitat insalubre (ou habitat indigne),Logement
2773,F16104,Habitat menaçant ruine (en péril),Logement
1992,F12903,Handicap : majoration pour la vie autonome (MVA),Social - Santé
1272,F14764,Handicap : peut-on cumuler la prestation de co...,Social - Santé
2807,F20055,"Impayés de factures (gaz, électricité, eau, té...",Logement
2502,F1226,Impôt sur le revenu - Avantages en nature,Argent - Impôts - Consommation
263,F5,Impôt sur le revenu - Frais d'accueil d'une pe...,Argent - Impôts - Consommation
1294,F410,Impôt sur le revenu - L'allocation chômage ou ...,Argent - Impôts - Consommation
1620,F32744,Impôt sur le revenu - Revenus d'une location m...,Argent - Impôts - Consommation
1655,F1991,Impôt sur le revenu - Revenus locatifs (locati...,Argent - Impôts - Consommation
1998,F34115,Impôt sur le revenu - Revenus locatifs d'un lo...,Argent - Impôts - Consommation
2707,F10752,Impôt sur le revenu - Travaux d'adaptation du ...,Argent - Impôts - Consommation
2439,F39380,Indemnisation des personnes expropriées,Logement
125,F13723,Indice de référence des loyers (IRL),Logement
2187,F642,Infractions aux règles d'urbanisme : quels son...,Logement
192,F34778,Inscription sur la liste électorale d'une pers...,Papiers - Citoyenneté - Élections
1846,F31404,Installation ou construction d'une piscine pri...,Logement
2327,F35782,Investissement locatif : quels sont les dispos...,Argent - Impôts - Consommation
619,F39735,Investissement locatif Relance logement - Jean...,Argent - Impôts - Consommation
1386,F15913,J'achète un logement,None
261,F14128,Je déménage en France,None
1949,F34635,Je pars de chez mes parents,None
2724,F31029,Je suis en situation de handicap,None
2916,F16123,Je veux obtenir un crédit immobilier,None
2125,F2289,Juridictions civiles de première instance,Justice
176,F35381,L'activité partielle de longue durée (APLD) ex...,"Social - Santé, Ressources humaines"
1285,F32037,"L'aide personnelle au logement (APL, ALF ou AL...",Logement
1937,F11678,L'allocation personnalisée d'autonomie (Apa) e...,Social - Santé
431,F31459,L'assureur peut-il résilier un contrat d'assur...,Argent - Impôts - Consommation
804,F1557,La tarification sociale de l'eau est-elle touj...,Logement
1351,F2407,La vente d'un bien immobilier est-elle soumise...,"Logement, Fiscalité"
476,F20237,Le RSA donne t-il droit à d'autres aides ?,Social - Santé
463,F2693,Le bail (ou contrat de location) peut-il inter...,Logement
345,F1857,Le locataire doit-il accorder un droit de visi...,Logement
2686,F31629,Le locataire peut-il payer le dernier mois de ...,Logement
2313,F1626,Le propriétaire choisit-il librement le locata...,Logement
2969,F32001,Le propriétaire d'un logement loué peut-il le ...,Logement
355,F31044,Le propriétaire d’un logement conventionné Ana...,Logement
2228,F31522,Le propriétaire est-il responsable des nuisanc...,Logement
2111,F2889,Le propriétaire peut-il facturer des frais de ...,Logement
2041,F2122,"Le salaire du concierge, gardien ou employé fa...",Logement
1176,F17554,Le siège d'une association peut-il être le dom...,"Associations, fondations et fonds de dotation"
2479,F896,Le syndic peut-il imposer une avance de trésor...,Logement
281,F31197,Les allocations chômage peuvent-elles être sup...,Social - Santé
81,F863,Les allocations familiales sont-elles saisissa...,Justice
2560,F33681,Licenciement abusif ou nul : l'employeur ou le...,Travail - Formation
1586,F2808,Licenciement économique d’un salarié : qu'est-...,Travail - Formation
2850,F34408,"Lille, Hellemmes et Lomme : montant du loyer p...",Logement
357,F1961,Liste électorale : inscription d'office à 18 a...,Papiers - Citoyenneté - Élections
320,F1793,Litige agricole : procès devant le tribunal pa...,Justice
1791,F2956,Livraison d'un logement vendu en état futur d'...,Logement
132,F31835,Local à poubelles d'un immeuble en copropriété...,Logement
561,F33208,Location d'un véhicule en leasing : comment ob...,Transports - Mobilité
1625,F2437,Location de voiture : LOA (location avec optio...,Argent - Impôts - Consommation
2722,F2721,Location saisonnière : comment assurer un meub...,Argent - Impôts - Consommation
1249,F39280,Location sociale de voitures électriques (Leas...,Transports - Mobilité
2635,F35978,Logement décent,Logement
371,F2559,Logement social : le bailleur peut-il résilier...,Logement
2301,F21051,Logement social : supplément de loyer de solid...,Logement
1216,F1170,Logement social : y a t-il transfert de bail e...,Logement
866,F31290,Logement social ou logement privé : quelles di...,Logement
2082,F2042,Logement à louer décent,Logement
1986,F1351,Logement à louer : dans quel cas signer une co...,Logement
933,F35323,Logement à louer : que doit indiquer l'annonce...,Logement
2426,F2541,Loyer d'un logement conventionné (Anah) : y a ...,Logement
2425,F1317,Loyer d'un logement social,Logement
857,F1312,Loyer sous-évalué d'un logement : hausse au re...,Logement
2178,F31272,Loyers impayés et expulsion du locataire,Logement
622,F36218,Lyon et Villeurbanne : montant du loyer pour u...,Logement
347,F38004,L’activité partielle de longue durée (APLD) « ...,"Social - Santé, Ressources humaines"
2896,F37501,MaPrimeAdapt' : travaux d'adaptation du logeme...,Logement

In [28]:
df_corpus_service_public = df_housing_candidates[
    df_housing_candidates["subject"]
    .fillna("")
    .str.contains("Logement", case=False)
].copy()

print("Corpus Service-Public retenu :", len(df_corpus_service_public))

Corpus Service-Public retenu : 350

In [29]:
df_corpus_service_public[
    ["document_id", "title", "subject"]
].sort_values("title")

,document_id,title,subject
1250,F37190,Achat d'un logement en copropriété,Logement
2693,F2762,Achat ou vente en viager : quelles sont les rè...,Logement
2497,F2961,Acte de vente d'un logement en l'état futur d'...,Logement
1686,F2962,Acte de vente d'un logement existant,Logement
1850,F12702,Acte de vente d'un terrain situé dans un lotis...,Logement
2606,F258,Acte de vente d'un terrain à bâtir isolé,Logement
2366,F1988,Affichage de l'autorisation d'urbanisme sur le...,Logement
62,F33173,Aide au logement : qu'est-ce que l'aide Mobili...,Logement
1884,F39682,Aide au retrait-gonflement des argiles (RGA) p...,Logement
1357,F1702,Aide aux travaux d'insonorisation d'un logemen...,Logement
1544,F12006,Aide personnalisée au logement (APL),Logement
2815,F1328,Aides financières de l'Anah pour réaliser des ...,Logement
947,F13132,Allocation de logement familiale (ALF),Logement
2552,F1280,Allocation de logement sociale (ALS),Logement
1978,F10538,"Ascenseur : sécurité, entretien et contrôle te...",Logement
1532,F447,Assainissement des eaux usées domestiques,Logement
1749,F2032,Assurance dommages-ouvrage (DO),Logement
2659,F37110,Audit énergétique en cas de vente d'un bien im...,Logement
1671,F1311,Augmentation et révision du loyer en cours de ...,Logement
2936,F18490,Avance Loca-Pass : aide au locataire pour le d...,Logement
2342,F31699,Bail d'habitation : travaux à la charge du pro...,Logement
104,F2066,Bail d’habitation : documents remis par le pro...,Logement
2945,F34769,Bail d’habitation : qu'est-ce qu'un logement m...,Logement
2706,F1165,Bail d’habitation : quelles différences entre ...,Logement
501,F36487,Bordeaux : montant du loyer pour un bail d'hab...,Logement
960,F3037,Bornage de terrains,Logement
3002,F20586,Budget prévisionnel d'une copropriété,Logement
1619,F2665,Carnet d'entretien de la copropriété,Logement
602,F36759,Carnet d'information du logement (CIL),Logement
1220,F31267,Caution du locataire ou du colocataire dans un...,Logement
1048,F1633,Certificat d'urbanisme (CU),"Logement, Secteurs d'activité"
2123,F35584,Certificats d'économie d'énergie (CEE),Logement
2767,F2590,Charges de copropriété,Logement
2515,F947,Charges à payer par le locataire (charges loca...,Logement
1032,F33667,Chèque énergie,Logement
2423,F1686,Clauses interdites dans un bail d'habitation,Logement
200,F34661,Colocation : quelles sont les règles ?,Logement
2930,F17709,Comment augmenter le loyer d'un logement soumi...,Logement
896,F32360,Comment calculer le délai de préavis en cas de...,Logement
2454,F1548,Comment changer de syndic de copropriété en fi...,Logement
2914,F18116,Comment choisir un fournisseur d'électricité o...,Logement
1517,F16832,Comment connaître le prix d'un logement ou d'u...,Logement
1017,F14226,Comment consulter le cadastre ?,Logement
2065,F172,Comment déclarer un projet de puits ou de fora...,Logement
648,F32051,Comment est rémunéré le syndic de copropriété ?,Logement
2130,F39760,Comment faire lorsque la copropriété n’a plus ...,Logement
2901,F664,Comment obtenir des informations sur la qualit...,Logement
2338,F17759,Comment obtenir des renseignements immobiliers ?,Logement
787,F2125,Comment obtenir un arrêté d'alignement individ...,Logement
1670,F2127,Comment se procurer la copie d'un règlement de...,Logement
2829,F2416,Comment transformer un local professionnel ou ...,Logement
2782,F34401,Complément de loyer : quelles sont les règles ?,Logement
824,F2610,Conseil syndical de copropriété,Logement
1733,F34554,Construire sa maison : quel contrat passer ave...,Logement
2804,F2963,Contrat de réservation d'un logement en vente ...,Logement
2330,F34825,Convention Anah : qu'apporte l'intermédiation ...,Logement
2286,F2615,Convocation de l'assemblée générale des coprop...,Logement
374,F2643,Copropriété en difficulté : intervention d'un ...,Logement
2939,F20388,Copropriété en difficulté : mesures préventive...,Logement
360,F2667,Copropriété en difficulté : état de carence,Logement
1334,F32088,Copropriété en graves difficultés : plan de sa...,Logement
1881,F14745,Copropriété : individualisation de la consomma...,Logement
201,F31513,Copropriété : travaux et aménagements dans l'a...,Logement
1228,F35202,Couple de concubins locataire de son logement ...,Logement
1267,F2562,Couple de concubins locataire de son logement ...,Logement
2903,F1159,Couple marié locataire de son logement : quell...,Logement
1863,F2565,Couple pacsé locataire de son logement : quell...,Logement
2134,F36622,Couple pacsé locataire de son logement : quell...,Logement
1958,F76,Création d'une ouverture ou d'un aménagement a...,Logement
2787,F37237,Dalo,Logement
786,F20568,Dans quel cas doit-on faire appel à un archite...,"Logement, Secteurs d'activité"
390,F33298,Dans quel cas le débroussaillement est-il obli...,Logement
2857,F1216,Dans quel cas saisir la commission département...,Logement
594,F35266,Diagnostic Bruit des aéroports (état des nuisa...,Logement
129,F37504,Diagnostic de performance énergétique collecti...,Logement
578,F31685,Diagnostic immobilier : assainissement des eau...,Logement
1281,F1142,Diagnostic immobilier : constat de risque d'ex...,Logement
1363,F16096,Diagnostic immobilier : diagnostic de performa...,Logement
1913,F742,"Diagnostic immobilier : état d'amiante ou ""dia...",Logement
2193,F18692,Diagnostic immobilier : état de l'installation...,Logement
2986,F17337,Diagnostic immobilier : état de l'installation...,Logement
2851,F12239,Diagnostic immobilier : état des risques,Logement
460,F32059,Diagnostic technique global (DTG) de la coprop...,Logement
280,F3150,Diagnostic termites et autres insectes xylophages,Logement
618,F17376,Diagnostics immobiliers : où trouver un diagno...,Logement
2919,F1722,Dispositif de sécurité des piscines privées fa...,Logement
2225,F33682,Doit-on obligatoirement entreprendre des trava...,Logement
802,F2443,Doit-on recevoir les eaux qui s'écoulent du te...,Logement
1723,F18005,Droit au logement opposable (Dalo) : faire val...,Logement
1632,F2040,Droit de passage sur le terrain d'un autre pro...,Logement
240,F39367,Droits des personnes expropriées,Logement
967,F35212,Déchets d'équipements électriques et électroni...,Logement
1327,F31955,Déchets d'équipements électriques et électroni...,Logement
2466,F1997,Déclaration attestant l'achèvement et la confo...,"Logement, Secteurs d'activité"
2740,F1992,Déclaration d'ouverture de chantier (DOC),"Logement, Secteurs d'activité"
1993,F17578,Déclaration préalable (DP),"Logement, Secteurs d'activité"
1296,F2103,Dégradations causées lors d'un cambriolage : q...,Logement
1708,F39713,Dépôt de garantie,Logement
634,F31269,Dépôt de garantie dans un bail d'habitation,Logement
2018,F2619,Déroulement d'une assemblée générale des copro...,Logement
1246,F19950,Détecteur de fumée : sécurité incendie dans le...,Logement
2557,F31418,Emprunt bancaire collectif d'une copropriété,Logement
465,F31672,"En cas de changement de syndic, que deviennent...",Logement
529,F1314,En quoi consiste l'encadrement des loyers à re...,Logement
1955,F31954,Encombrants (déchets volumineux),Logement
2976,F20760,Entretien annuel de la chaudière : quelles règ...,Logement
2344,F31697,Entretien courant et réparations locatives à l...,Logement
1031,F36219,Est Ensemble : montant du loyer pour un bail d...,Logement
1837,F31963,Existe-il une amende pour abandon de déchets d...,Logement
733,F35683,Faire une demande de logement social,Logement
127,F10007,Faire une demande de logement social (HLM),Logement
541,F15133,Faut-il déneiger le trottoir situé devant son ...,Logement
1969,F37294,Faut-il un état daté pour vendre un logement d...,Logement
1178,F36775,Faut-il une autorisation d'urbanisme pour amén...,Logement
1550,F37925,Faut-il une autorisation d'urbanisme pour cons...,Logement
2192,F37923,Faut-il une autorisation d'urbanisme pour cons...,Logement
2947,F36780,Faut-il une autorisation d'urbanisme pour inst...,Logement
1368,F31923,Faut-il une autorisation d'urbanisme pour pose...,"Logement, Secteurs d'activité, Environnement"
1631,F36798,Faut-il une autorisation d'urbanisme pour pose...,Logement
2376,F37976,Faut-il une autorisation pour diviser un bâtim...,Logement
2991,F34051,Fiche synthétique de la copropriété,Logement
2854,F34026,Fonds de travaux mis en place dans les copropr...,Logement
2615,F375,Frais d'agence immobilière à la location d'un ...,Logement
829,F1169,Futur locataire d'un logement privé : justific...,Logement
1132,F33453,Garantie Visale : caution pour le locataire (i...,Logement
2506,F34253,Garantie de livraison d'une maison individuelle,Logement
1052,F2034,Garantie décennale des constructeurs,"Logement, Secteurs d'activité"
1276,F2958,Garanties après la réception des travaux,Logement
1219,F39137,Grenoble-Alpes Métropole : montant du loyer po...,Logement
2677,F288,Habitat contenant de l'amiante,Logement
1582,F1141,Habitat contenant du plomb,Logement
2964,F20599,Habitat contenant du radon,Logement
1994,F16158,Habitat insalubre (ou habitat indigne),Logement
2773,F16104,Habitat menaçant ruine (en péril),Logement
2807,F20055,"Impayés de factures (gaz, électricité, eau, té...",Logement
2439,F39380,Indemnisation des personnes expropriées,Logement
125,F13723,Indice de référence des loyers (IRL),Logement
2187,F642,Infractions aux règles d'urbanisme : quels son...,Logement
1846,F31404,Installation ou construction d'une piscine pri...,Logement
1285,F32037,"L'aide personnelle au logement (APL, ALF ou AL...",Logement
804,F1557,La tarification sociale de l'eau est-elle touj...,Logement
1351,F2407,La vente d'un bien immobilier est-elle soumise...,"Logement, Fiscalité"
463,F2693,Le bail (ou contrat de location) peut-il inter...,Logement
345,F1857,Le locataire doit-il accorder un droit de visi...,Logement
2686,F31629,Le locataire peut-il payer le dernier mois de ...,Logement
2313,F1626,Le propriétaire choisit-il librement le locata...,Logement
2969,F32001,Le propriétaire d'un logement loué peut-il le ...,Logement
355,F31044,Le propriétaire d’un logement conventionné Ana...,Logement
2228,F31522,Le propriétaire est-il responsable des nuisanc...,Logement
2111,F2889,Le propriétaire peut-il facturer des frais de ...,Logement
2041,F2122,"Le salaire du concierge, gardien ou employé fa...",Logement
2479,F896,Le syndic peut-il imposer une avance de trésor...,Logement
2850,F34408,"Lille, Hellemmes et Lomme : montant du loyer p...",Logement
1791,F2956,Livraison d'un logement vendu en état futur d'...,Logement
132,F31835,Local à poubelles d'un immeuble en copropriété...,Logement
2635,F35978,Logement décent,Logement
371,F2559,Logement social : le bailleur peut-il résilier...,Logement
2301,F21051,Logement social : supplément de loyer de solid...,Logement
1216,F1170,Logement social : y a t-il transfert de bail e...,Logement
866,F31290,Logement social ou logement privé : quelles di...,Logement
2082,F2042,Logement à louer décent,Logement
1986,F1351,Logement à louer : dans quel cas signer une co...,Logement
933,F35323,Logement à louer : que doit indiquer l'annonce...,Logement
2426,F2541,Loyer d'un logement conventionné (Anah) : y a ...,Logement
2425,F1317,Loyer d'un logement social,Logement
857,F1312,Loyer sous-évalué d'un logement : hausse au re...,Logement
2178,F31272,Loyers impayés et expulsion du locataire,Logement
622,F36218,Lyon et Villeurbanne : montant du loyer pour u...,Logement
2896,F37501,MaPrimeAdapt' : travaux d'adaptation du logeme...,Logement
1534,F35083,MaPrimeRénov' (MPR),Logement
406,F37827,MaPrimeRénov' Copropriété,Logement
1957,F31473,Maison : travaux extérieurs,Logement
2438,F14748,Micro-logement : doit-on payer une taxe en cas...,Logement
738,F19450,Modification d'une autorisation d'urbanisme,"Logement, Secteurs d'activité"
2383,F1310,Montant du loyer d'un logement appartenant à u...,Logement
1314,F36437,Montpellier : montant du loyer pour un bail d'...,Logement
2583,F2415,Mur mitoyen,Logement
2128,F20762,Médiateur de l'eau : comment y recourir ?,Logement
2085,F20820,Médiateur national de l'énergie : comment y re...,Logement
2161,F31300,Obligation du locataire : assurance habitation...,"Argent - Impôts - Consommation, Logement"
2761,F31487,Obtenir de l'électricité avec des panneaux sol...,Logement
2601,F31488,Obtenir de la chaleur à l'aide d'une installat...,Logement
2484,F16217,Ordures ménagères,Logement
120,F34396,Paiement du loyer d'un logement du secteur pri...,Logement
1633,F1214,Paiement du loyer par le locataire (bail d’hab...,Logement
2609,F34407,Paris : montant du loyer pour un bail d'habita...,Logement
1339,F31518,Partie commune réservée à l'usage exclusif d'u...,Logement
1485,F31512,Parties privatives réservées à l'usage exclusi...,Logement
28,F38659,Pays Basque : montant du loyer pour un bail d'...,Logement
2507,F17665,Permis d'aménager,"Logement, Secteurs d'activité"
2516,F1986,Permis de construire (PC),Logement
337,F17669,Permis de démolir,"Logement, Secteurs d'activité"
1414,F31527,Peut-on accrocher librement des objets aux fen...,Logement
9,F282,Peut-on acheter son logement social ?,Logement
60,F31858,Peut-on brûler des déchets verts (végétaux) da...,Logement
2387,F3107,Peut-on changer l'affectation d'un lot de copr...,Logement
48,F31601,Peut-on conserver son logement social en cas d...,Logement
2204,F924,Peut-on construire ou aménager un terrain en z...,Logement
872,F20567,Peut-on contester une autorisation d'urbanisme...,Logement
1387,F35288,Peut-on contester une décision prise en assemb...,Logement
2494,F31644,Peut-on créer un syndicat secondaire dans un g...,Logement
1793,F20554,Peut-on encore bénéficier de MaPrimeRénov' Sér...,Logement
2404,F37655,Peut-on encore bénéficier de la Prime « Coup d...,Logement
1609,F1613,Peut-on encore bénéficier des aides à l'adapta...,Logement
2402,F33663,Peut-on faire annuler une décision de préempti...,Logement
1922,F10696,Peut-on faire payer les frais d'état des lieux...,Logement
887,F15837,Peut-on forcer un propriétaire à insonoriser s...,Logement
2315,F34210,Peut-on mettre en location un logement dans un...,Logement
990,F31671,Peut-on mettre fin au mandat en cours d'un syn...,Logement
1165,F67,Peut-on passer sur le terrain de son voisin po...,Logement
78,F36956,Peut-on reconstruire un bâtiment après sa dest...,Logement
293,F19069,Peut-on revendre son logement avant d'avoir re...,Logement
135,F1703,Peut-on se rétracter après avoir signé un bail...,Logement
932,F620,Peut-on stationner une caravane ou installer u...,Logement
1591,F1239,Peut-on échanger son logement social (HLM) ent...,Logement
885,F35108,Piscine,Logement
1783,F35761,Plaine Commune : montant du loyer pour un bail...,Logement
528,F36760,Plan pluriannuel de travaux (PPT) mis en place...,Logement
2889,F614,"Plantation de végétaux (haies, arbres, bambous...",Logement
1318,F34421,"Prime ""Coup de pouce Chauffage""",Logement
2855,F35755,Prime Coup de pouce Rénovation d'ampleur des m...,Logement
874,F35779,Prime Coup de pouce Rénovation performante de ...,Logement
1383,F2636,Procès-verbal d'assemblée générale des copropr...,Logement
2328,F762,Procédure d’expropriation,Logement
1981,F2965,Promesse de vente d'un logement existant : pro...,Logement
1067,F2057,Promesse de vente d'un terrain isolé à bâtir,Logement
2893,F16455,Promesse de vente d'un terrain situé dans un l...,Logement
1418,F1168,Préavis et formalités du congé donné par le lo...,Logement
2743,F929,Préavis et formalités du congé donné par le pr...,Logement
2801,F38425,Prêt avance mutation ne portant pas intérêt (é...,Logement
2633,F1616,Prêt à l'amélioration de l'habitat (PAH),Logement
2331,F39003,Prêt à l'amélioration du lieu d'accueil (PALA)...,Logement
778,F10039,Qu'est-ce qu'un bail de sortie progressive de ...,Logement
1917,F1219,Qu'est-ce qu'un logement soumis à la loi de 19...,Logement
2262,F188,Qu'est-ce qu'une condition suspensive d'obtent...,Logement
1589,F2753,Qu'est-ce qu'une offre d'achat d'un bien immob...,Logement
1497,F33877,Qu'est-ce que le règlement intérieur de coprop...,Logement
1404,F34736,Quand s'applique la trêve hivernale ?,Logement
2973,F33664,Que devient le bail d'un locataire dont le log...,Logement
275,F32061,Que doit indiquer l'annonce d'une vente immobi...,Logement
779,F13737,Que faire en cas d'attroupement dans son immeu...,Logement
2289,F389,Que faire en cas d'augmentation anormale de sa...,Logement
931,F1176,Que faire en cas d'utilisation abusive d'un ba...,Logement
665,F31301,Que faire en cas de litige lié à la location d...,Logement
2281,F2618,Que faire lorsque l'on a perdu l'acte de propr...,Logement
182,F35254,Que faire quand des squatteurs occupent un log...,Logement
2433,F32305,Que faire quand le locataire abandonne le loge...,Logement
693,F1525,Que faire si le terrain d’un voisin n’est pas ...,Logement
2564,F289,Que risque le propriétaire d'un immeuble ou d'...,Logement
919,F2533,Quel contrat passer avec une entreprise pour d...,Logement
2746,F479,Quel est le délai de prescription d'une dette ...,Logement
2118,F32973,Quel est le tarif d’un huissier (à présent app...,Logement
16,F1550,Quel mandat de vente peut-on confier à un agen...,Logement
256,F1334,Quelle aide apporte le Fonds de solidarité pou...,Logement
21,F36762,Quelle autorisation d'urbanisme déposer pour c...,Logement
2234,F24612,Quelle autorisation d'urbanisme déposer pour c...,Logement
1315,F36768,Quelle autorisation d'urbanisme déposer pour c...,Logement
2396,F36767,Quelle autorisation d'urbanisme déposer pour f...,Logement
588,F36777,Quelle autorisation d'urbanisme déposer pour f...,Logement
2112,F662,Quelle autorisation d'urbanisme déposer pour i...,"Logement, Secteurs d'activité"
1757,F31471,Quelle autorisation d'urbanisme déposer pour i...,Logement
1785,F36773,Quelle autorisation d'urbanisme déposer pour i...,Logement
2133,F36774,Quelle autorisation d'urbanisme faut-il dépose...,Logement
646,F36778,Quelle autorisation d'urbanisme faut-il dépose...,Logement
205,F36766,Quelle autorisation d'urbanisme faut-il dépose...,Logement
728,F36779,Quelle autorisation d'urbanisme faut-il dépose...,Logement
1636,F37932,Quelle autorisation d'urbanisme faut-il pour d...,Logement
2147,F35336,Quelle autorisation déposer pour faire un chan...,"Logement, Secteurs d'activité"
1033,F36776,Quelle autorisation d’urbanisme déposer pour c...,Logement
175,F34905,Quelle est la hauteur et la surface minimum d'...,Logement
2159,F481,Quelle est la hauteur réglementaire d'un garde...,Logement
961,F31911,Quelles aides financières peut-on percevoir po...,Logement
1244,F34339,Quelles précautions prendre avant l'achat d'un...,Logement
2699,F33818,Quelles précautions prendre avant l'achat d'un...,Logement
2440,F36909,Quelles questions d'urbanisme se poser avant d...,Logement
2729,F31475,Quelles règles respecter pour installer un jac...,Logement
2482,F2073,Quelles sont les conditions de vente d’un terr...,Logement
2007,F869,Quelles sont les conditions pour obtenir un lo...,Logement
383,F31864,Quelles sont les différences entre les aides p...,Logement
319,F2484,Quelles sont les obligations du vendeur d'un t...,Logement
2834,F34759,Quelles sont les règles d'un bail mobilité ?,Logement
1545,F14747,Quelles sont les règles de location d'une plac...,Logement
971,F2315,Quelles sont les règles de location que le pro...,Logement
325,F2137,Quelles sont les règles de vote en assemblée g...,Logement
1736,F36961,Quelles sont les règles d’urbanisme à respecte...,Logement
194,F37924,Quelles sont les règles d’urbanisme à respecte...,Logement
1126,F3131,Quelles sont les règles pour construire ou ins...,"Logement, Secteurs d'activité"
1170,F33463,Quels sont les diagnostics immobiliers qu’un b...,Logement
1356,F10798,Quels sont les diagnostics immobiliers à fourn...,Logement
2931,F35742,Quels sont les travaux à déclarer aux impôts ?,"Logement, Secteurs d'activité"
1286,F31531,Qui est prioritaire pour acheter un bien dans ...,Logement
1646,F21105,Qui est responsable des dégradations dans un l...,Logement
2723,F32920,Qui paie les charges de copropriété l'année de...,Logement
143,F11384,Qui peut assister aux réunions du conseil synd...,Logement

In [30]:
CORPUS_META_PATH = os.path.join(
    PROJECT_PATH,
    "data",
    "processed",
    "service_public_logement_metadata.csv"
)

df_corpus_service_public.to_csv(
    CORPUS_META_PATH,
    index=False,
    encoding="utf-8-sig"
)

print("Sauvegardé :", CORPUS_META_PATH)

Sauvegardé : /content/drive/MyDrive/Assistant_HLM_RAG/data/processed/service_public_logement_metadata.csv